import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { GlobalAIFab } from "@/components/global-ai-fab";

export const metadata: Metadata = {
  title: "Canvas智能助手",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/icon/CanvasIcon64x64.ico', sizes: '64x64', type: 'image/x-icon' },
      { url: '/icon/CanvasIcon256x256.ico', sizes: '256x256', type: 'image/x-icon' },
    ],
    apple: '/icon/CanvasEduBotIcon.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased flex flex-col min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex-grow bg-background text-foreground">{children}</main>
          <GlobalAIFab />
          <footer className="border-t py-4 px-6 text-center text-sm text-muted-foreground bg-background">
            © 猪头Canvas会不会遇上Agent学姐 | 基于 Canvas 开发
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
